insert tables and gffa_utils udpated
umsi-arwhyte/gffa-db pull request #7
Opened 2022-05-15 22:34 UTC by ShaiviGanatra

insert_tables.py
- sentient_being, vehicle class, vehicle type and vehicle added with foreign keys dependencies.
- vehicle_type_id in vehicle says 1 for temp

gffa_utils.py
- Function get_index_from_url added to support search for foreign keys across tables while insertions using regex.

2022-05-16 18:31 UTC, arwhyte requested changes

2022-05-16 18:31 UTC, arwhyte commented on gffa_utils.py
> +        print("TESTING")
comment out `print()` function calls

2022-05-16 18:31 UTC, arwhyte commented on gffa_utils.py
> +        if type(value) == str:
Use `isinstance()` instead.

2022-05-16 18:31 UTC, arwhyte commented on insert_tables.py
> +    sentient_being_attr = dict((k, sentient_being[k]) for k in ['height', 'mass', 'hair_color', 'skin_color', 'eye_color', 'birth_year', 'gender', 'films', 'species', 'vehicles', 'starships'])
convert this line to a dictionary comprehension rather than calling `dict()`.

2022-05-16 18:31 UTC, arwhyte commented on insert_tables.py
> +    vehicle_attr = dict((k, vehicle[k]) for k in ['model'])
Convert to dict comprehension.

2022-05-27 16:17 UTC, arwhyte requested changes

2022-05-27 16:17 UTC, arwhyte commented on gffa_utils.py
> +from sys import intern
Check this import and if unnecessary remove it.

2022-06-10 14:59 UTC, ShaiviGanatra commented
Updates as per datamodel 1.5

- unnecessary print and imports removed
- dict comprehension used for all tables
- isinstance() added in utils
- vehicle, vehicle_class and vehicle_type revised
- vehicle_class.vehicle_type_id pending

2022-06-10 15:13 UTC, arwhyte approved these changes

2022-06-10 15:15 UTC, merged